### ISSUE TITLE
Using methods in  XbimSemanticAnalyser and XbimSpatialAnalyser classes

### ISSUE THREAD

**Issue by atazadeh** [xBimTeam/XbimAnalysis#1]
Hi,

I want to use methods in spatial part of XbimAnalysis. But, after compiling the XbimAnalysis project and adding Xbim.Analysis dll reference, there is no Xbim.Analysis.Spatial namespace to use. I also changed "Build Action" property of all classes under spatial folder and tried to compile the XbimAnalysis project. But, in this case two errors happens in XbimSpatialAnalyser class. First, it seems that there is no definition for Geometry3D() method. Second, CreateContext() does not accept "true" as its argument.

![capture 1png](https://cloud.githubusercontent.com/assets/8553060/8124446/d7492396-111e-11e5-83e7-0c41da466726.PNG)

I would appreciate if anyone please let me know how to resolve this issue and call the methods like Disjoint and Intersection.

Regards,
Benham

**Comment by martin1cerny** [comment]
Hi Benham,

thank you for rising this issue. Geometry engine has undergone major restructuring and recoding in last 9 months and it hasn't been upgraded in this project so far. Also, this project was created about 2 years ago and I'm sorry to say that spatial analyses are not fully implemented so far. We are looking into this but only semantic analyses work for now. Functions like "Disjoint()" will only evaluate bounding boxes and will fail to evaluate exact geometry.

![snippet](https://cloud.githubusercontent.com/assets/773078/8157010/60d86b06-1351-11e5-9085-42e25c4e8477.PNG)

However, new geometry engine has built-in support for low-level geometry analyses so it should be possible to implement this quite easily. Octree algorithm is also implemented already to make spatial-relation queries easier to do.

So, stay tuned. We would like to have this GIS-like functionality implemented. If you would like to help us with this we would appreciate it a lot.

Regards

Martin

**Comment by atazadeh** [comment]
Hi Martin,

Thank you very much for your reply. As you mentioned, the semantic queries work fine.  I am interested and will try to find out how to perform geometric queries. 

Regards,
Behnam

**Comment by martin1cerny** [comment]
Hi Benham,

your  best bet for this is to have a look in [XbimGeometry](https://github.com/xBimTeam/XbimGeometry) project. All spatial operations can be done there. It is a hard stuff as you will have known if you are after spatial queries and relations. Do you have any specific use for this kind of functionality? Does it have anything to do with GIS or is it only for a collisions?

**Comment by atazadeh** [comment]
Hi Martin, 
Thanks. I am interested in using BIM for GIS- based applications. As part of my phd research at Melbourne Uni, I want to explore how topological queries can be done in BIM environment. This is useful for finding ownership boundaries within buildings. For example, we can say what physical structures determine the boundary of a private or common property inside a building. The boundary can touch interior face of a physical building element or it can intersect through the middle of physical structure or it can cover the physical building element (exterior). I think Ifc data model supports interior case as it relates IfcSpace to physical building elements through IfcRelSpaceBoundary relationship (semantic touch query can be done here to find boundary). However, for middle and exterior boundaries, I need to do geometric queries (intersection and covers).

I would appreciate if you let me know your opinion about this.

Regards,
Behnam

**Comment by martin1cerny** [comment]
Very nice, I did my PhD on something very similar. There are many more relations defined in IFC which you can check for this. Especially _IfcRelContainedInSpatialStructure_ and _IfcRelReferencedInSpatialStructure_ might be interesting for you. But you are right that geometry is also important to check. Here is an image from my [dissertation](https://www.vutbr.cz/studium/zaverecne-prace?zp_id=82843):

![simple_floor_plan_relations_and_geometry](https://cloud.githubusercontent.com/assets/773078/8228967/38f003ba-15b3-11e5-83b6-3e1f03be7bc9.png)

**Comment by atazadeh** [comment]
Hi Martin,

Thank you very much for sharing your PhD thesis, which is a very good citation for my research. I had a glance at it and find it very interesting research project. Do you have any publication in English? Thanks.

Regards,
Behnam

**Comment by martin1cerny** [comment]
Unfortunately I don't. It was easier to do it in Czech at the time. But if
you have any specific questions I'm happy to share my findings.

Martin

2015-06-19 7:47 GMT+02:00 atazadeh notifications@github.com:

**Comment by atazadeh** [comment]
Thanks very much Martin. I will contact you in case that I have a question.
I would appreciate if you can provide me with your email address.

Regards,
Behnam

**Comment by martin1cerny** [comment]
Hi Benham,

You can reach me on martin1cerny@gmail.com.

Martin

Dne 19.6.2015 v 14:08 atazadeh napsal(a):

> Thanks very much Martin. I will contact you in case that I have a 
> question.
> I would appreciate if you can provide me with your email address.
> 
> Regards,
> Behnam
>
